#ifndef __SERIALMONITOR_PAGE_H__
#define __SERIALMONITOR_PAGE_H__
#include <Arduino.h>


String WEB_SERIALMONITOR_PAGE = ""
    "<div class='card border-info mb-3'>"
        "<div class='card-header'>"
            "<h3>Port</h3>"
        "</div>"
        "<div class='card-body'>"
            "<div class='btn-toolbar mb-3' role='toolbar'>"
                "<div class='btn-group' role='group'>"
                    "<button class='btn btn-outline-secondary' type='button' id='connectButton'>Connect</button>"
                "</div>"
                "<div class='btn-group' role='group'>"
                    "<button class='btn btn-outline-secondary dropdown-toggle' type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='selected_serial'>HW Serial 1</button>"
                    "<div class='dropdown-menu' id='sel_serial'>"
                        "<a class='dropdown-item' href='#' data-value='0'>HW Serial 0</a>"
                        "<a class='dropdown-item' href='#' data-value='1'>HW Serial 1</a>"
                        "<a class='dropdown-item' href='#' data-value='2'>SoftwareSerial</a>"
                    "</div>"
                "</div>"
                "<div class='input-group'>"          
                    "<div class='input-group-prepend'>"
                        "<div class='input-group-text' id='btnGroupAddon'>RX Pin</div>"
                    "</div>"
                    "<input type='text' class='form-control' placeholder='' aria-label='' id='selected_rxpin'>"
                "</div>"
                "<div class='input-group'>"          
                    "<div class='input-group-prepend'>"
                        "<div class='input-group-text' id='btnGroupAddon'>TX Pin</div>"
                    "</div>"
                    "<input type='text' class='form-control' placeholder='' aria-label='' id='selected_txpin'>"
                "</div>"
                "<div class='btn-group' role='group'>"
                    "<button class='btn btn-outline-secondary dropdown-toggle' type='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false' id='selected_baudrate'>Baudrate 115200</button>"
                    "<div class='dropdown-menu' id='sel_baudrate'>"
                        "<a class='dropdown-item' href='#' data-value='300'>300</a>"
                        "<a class='dropdown-item' href='#' data-value='600'>600</a>"
                        "<a class='dropdown-item' href='#' data-value='1200'>1.200</a>"
                        "<a class='dropdown-item' href='#' data-value='2400'>2.400</a>"
                        "<a class='dropdown-item' href='#' data-value='4800'>4.800</a>"
                        "<a class='dropdown-item' href='#' data-value='9600'>9.600</a>"
                        "<a class='dropdown-item' href='#' data-value='14400'>14.400</a>"
                        "<a class='dropdown-item' href='#' data-value='19200'>19.200</a>"
                        "<a class='dropdown-item' href='#' data-value='28800'>28.800</a>"
                        "<a class='dropdown-item' href='#' data-value='38400'>38.400</a>"
                        "<a class='dropdown-item' href='#' data-value='56000'>56.000</a>"
                        "<a class='dropdown-item' href='#' data-value='57600'>57.600</a>"
                        "<a class='dropdown-item' href='#' data-value='115200'>115.200</a>"
                        "<a class='dropdown-item' href='#' data-value='128000'>128.000</a>"
                        "<a class='dropdown-item' href='#' data-value='256000'>256.000</a>"
                    "</div>"
                "</div>"
            "</div>"
        "</div>"
        "<div class='card-footer'>"
        "</div>"
    "</div>"
    "<div class='card border-info mb-3'>"
        "<div class='card-header'>"
            "<h3>Communication</h3>"
        "</div>"
        "<div class='card-body'>"
            "<textarea class='form-control' id='uartcom' rows='10'></textarea>"
        "</div>"
        "<div class='card-footer'>"
            "<form method='post' action='#' enctype='multipart/form-data' id='postform'>"
                "<input class='form-control' type='text' name='senddata' id='senddata'>"
                "<button class='btn btn-primary' type='submit'>Send</button>"
            "</form>"
        "</div>"
    "</div>"
;

String WEB_SERIALMONITOR_PAGE_SCRIPT = "<script>"
        "$(document).ready(function() {"
            "var selectedSerial = ###SERIAL###;"
            "var selectedBaudrate = ###BAUD###;"
            "var rxpinSelected = ###RXPIN###;"
            "var txpinSelected = ###TXPIN###;"
            "var connected = ###CONNECTED###;"
            "var requestLock = false;"

            "setInterval(function() {"
                "if (connected && !requestLock) {"
                    "requestLock = true;"
                    "$.ajax({"
                        "url : '/uartrx',"
                        "dataType: 'text',"
                        "success : function (data) {"
                            "var text = $('#uartcom').text();"
                            "text += data;"
                            "$('#uartcom').text(text);"
                            "$('#uartcom').scrollTop($('#uartcom')[0].scrollHeight);"
                            "requestLock = false;"
                        "},"
                        "error: function (a, b, c) {"
                            "requestLock = false;"
					    "}"
                    "});"
                "}"
            "}, 1000);"
            "$('#postform').submit(function(e) {"
                "e.preventDefault(e);"
                "var form = $('#postform')[0];"
			    "var data = new FormData(form);"
                "requestLock = true;"
                "$.ajax({"
                    "url: '/uarttx',"
                    "type: 'POST',"
                    "data: data,"
                    "contentType: false,"
					"processData:false,"
                    "success:function(d, s) {"
                        "$('#senddata').val('');"
                        "requestLock = false;"
				    "},"
					"error: function (a, b, c) {"
                        "requestLock = false;"
					"}"
                "});"
                "return false;"
            "});"


            "$('#sel_baudrate').on('click', 'a', function (e) {"
                "e.preventDefault(e);"
                "$('#selected_baudrate').text('Baudrate ' + $(this).data('value'));"
                "$('#selected_baudrate').data('value', $(this).data('value'));"
            "});"

            "$('#sel_serial').on('click', 'a', function (e) {"
                "e.preventDefault(e);"
                "$('#selected_serial').text($(this).text());"
                "$('#selected_serial').data('value', $(this).data('value'));"
                "if($(this).data('value') == 0) { "
                    "$('#selected_rxpin').val(1);"
                    "$('#selected_txpin').val(3);"
                    "$('#selected_rxpin').prop('disabled', true);"
                    "$('#selected_txpin').prop('disabled', true);"
                "}"
                "if($(this).data('value') == 1) { "
                    "$('#selected_rxpin').val(13);"
                    "$('#selected_txpin').val(15);"
                    "$('#selected_rxpin').prop('disabled', true);"
                    "$('#selected_txpin').prop('disabled', true);"
                "}"
                "if($(this).data('value') == 2) { "
                    "$('#selected_rxpin').prop('disabled', false);"
                    "$('#selected_txpin').prop('disabled', false);"
                "}"
            "});"
            
            "$('#connectButton').on('click', function (e) {"
                "e.preventDefault(e);"
                "var target = '/uartconnect';"
                "if (!connected) {"
                    "target += '?serial=' + $('#selected_serial').data('value');"
                    "target += '&baudrate=' + $('#selected_baudrate').data('value');"
                    "target += '&rxpin=' + $('#selected_rxpin').val();"
                    "target += '&txpin=' + $('#selected_txpin').val();"
                "} else {"
                    "target = '/uartdisconnect';"
                "}"
                "requestLock = true;"
                "$.ajax({"
                    "url: target,"
                    "type: 'GET',"
                    "contentType: false,"
                    "processData:false,"
                    "success:function(d, s) {"
                        "connected = !connected;"
                        "if (connected) {"
                            "$('#connectButton').text('Disconnect');"
                            "$('#selected_rxpin').prop('disabled', true);"
                            "$('#selected_txpin').prop('disabled', true);"
                            "$('#selected_serial').prop('disabled', true);"
                            "$('#selected_baudrate').prop('disabled', true);"
                        "} else {"
                            "$('#connectButton').text('Connect');"
                            "if((selectedSerial == 0) || (selectedSerial == 1)) { "
                                "$('#selected_rxpin').prop('disabled', true);"
                                "$('#selected_txpin').prop('disabled', true);"
                            "} else {"
                                "$('#selected_rxpin').prop('disabled', false);"
                                "$('#selected_txpin').prop('disabled', false);"
                            "}"
                            "$('#selected_serial').prop('disabled', false);"
                            "$('#selected_baudrate').prop('disabled', false);"
                        "}"
                        "requestLock = false;"
                    "},"
                    "error: function (a, b, c) {"
                        "requestLock = false;"
                    "}"
                "});"
            "});"

            "if((selectedSerial == 0) || (selectedSerial == 1)) { "
                "$('#selected_serial').text('HW Serial ' + selectedSerial);"
                "$('#selected_rxpin').prop('disabled', true);"
                "$('#selected_txpin').prop('disabled', true);"
            "} else {"
                "$('#selected_serial').text('SoftwareSerial');"
                "$('#selected_rxpin').prop('disabled', false);"
                "$('#selected_txpin').prop('disabled', false);"
            "}"
            "$('#selected_serial').data('value', selectedSerial);"
            "$('#selected_baudrate').text('Baudrate ' + selectedBaudrate);"
            "$('#selected_baudrate').data('value', selectedBaudrate);"
            "$('#selected_rxpin').val(rxpinSelected);"
            "$('#selected_txpin').val(txpinSelected);"
        "});"
    "</script>"
;



#endif /* #ifndef __SERIALMONITOR_PAGE_H__ */