#ifndef __UPLOAD_PAGE_H__
#define __UPLOAD_PAGE_H__
#include <Arduino.h>
#include "mainPageData.h"

String WEB_UPLOAD_PAGE = "<form method='POST' action='#' enctype='multipart/form-data' id='upload_form'>"
				"<div class='card border-info mb-3'>"
					"<div class='card-header'>"
						"<h3>Upload an binary file</h3>"
					"</div>"
					"<div class='card-body'>"
						"<div class='form-row'>"
							"<div class='col-md-4 mb-3'>"
								"<div class='update' style='background-color: lightgray; border: 1px solid black;'>"
									"<input type='file' name='update' id='update'>"
								"</div>"
							"</div>"
						"</div>"
					"</div>"
					"<div class='card-footer'>"
						"<div class='col-md-4 mb-3'>"
							"<button class='btn btn-primary' type='submit'>Update</button>"
						"</div>"
						"<div class='progress'>"
							"<div id='prg' class='progress-bar' role='progressbar' style='width: 0%;' aria-valuenow='0' aria-valuemin='0' aria-valuemax='100'>0%</div>"
						"</div>"
					"</div>"
				"</div>"
			"</form>"
			"<div class='card border-info mb-3'>"
				"<div class='card-header'>"
						"<h3>Upload over ArduinoOTA</h3>"
					"</div>"
					"<div class='card-body'>"
						"Upload over arduino OTA<br>"
						"%target%"
					"</div>"
				"</div>"
			"</div>"
		"</div>";
		
String WEB_UPLOAD_PAGE_SCRIPT = "<script>"
		"$('form').submit(function(e){"
			"e.preventDefault();"
			  "var form = $('#upload_form')[0];"
			  "var data = new FormData(form);"
			   "$.ajax({"
					"url: '/update',"
					"type: 'POST',"
					"data: data,"
					"contentType: false,"
					"processData:false,"
					"xhr: function() {"
						"var xhr = new window.XMLHttpRequest();"
						"xhr.upload.addEventListener('progress', function(evt) {"
							"if (evt.lengthComputable) {"
								"var per = evt.loaded / evt.total;"
								"$('#prg').html('' + Math.round(per*100) + '%');"
								"$('#prg').width('' + Math.round(per*100) + '%');"
								"if (Math.round(per*100) >= 100) {"
									"setTimeout("
										"function() {"
											"window.location.href='/';"
										"}, 1000);"
								"}"
							"}"
					   "}, false);"
					   "return xhr;"
					"},"
					"success:function(d, s) {"
						"console.log('success!');"
						"setTimeout("
  							"function() {"
    							"window.location.href='/';"
  							"}, 800);"
				   "},"
					"error: function (a, b, c) {"
					"}"
				  "});"
		"});"
		"</script>";

#endif /* #ifndef __UPLOAD_PAGE_H__ */